from ..helper import *
### from helper import * # only testing
from ..skills.market_data import *
### from skills.market_data import * # only testing
from google.adk.models.google_llm import Gemini
from google.adk.agents import Agent

config = get_model_config("writer_agent")


writer_agent = Agent(
    name="Financial_Writer",
    model=Gemini(
        model=config["model_name"],        
        retry_options=get_retry_config()
    ),
    description="Agent responsible for writing the financial report based on the research plan and data fetched by tools.",
    instruction="""
    You are a Senior Financial Content Specialist. 
    
    YOUR OBJECTIVE:
    1. Read the research plan generated by the Planner: {{research_plan}}.
    2. Use your TOOLS to fetch the specific data points requested in that plan.
    3. Synthesize the raw JSON data into a professional, narrative financial report.
    
    REPORT STRUCTURE:
    - Executive Summary: High-level takeaway.
    - Data Analysis: Breakdown of stock stats and sector performance.
    - Conclusion: Strategic outlook based on the data.
    
    IMPORTANT: Do not hallucinate numbers. If a tool returns an error, state that the data is unavailable.
    """,
    tools=[get_stock_stats, get_sector_performance],
    output_key="draft_report",  # The result of this agent will be stored in the session state with this key.
)
